### ISSUE TITLE
perlcritic test fails

### ISSUE THREAD

**Issue by eserte** [kan/p5-dbic-random-string-columns#1]
See subject. More information:
- http://analysis.cpantesters.org/solved?distv=DBIx-Class-RandomStringColumns-0.09
- http://matrix.cpantesters.org/?dist=DBIx-Class-RandomStringColumns%200.09

**Comment by kan** [comment]
Thank you report. I'll fix that.

**Comment by kan** [comment]
https://metacpan.org/release/MIKIHOSHI/DBIx-Class-RandomStringColumns-0.10
